[package]
name = "balatro-card-drawing-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = "0.59.0"
combinatorial = "0.2.1"
derive-new = "0.7.0"
enum-iterator = "2.3.0"
json = "0.12.4"
lazy_static = "1.5.0"
malachite = { version = "0.9.1", features = ["enable_serde"] }
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[[bin]]
name = "count_1"

[[bin]]
name = "count_2"

[[bin]]
name = "simulate"

[[bin]]
name = "generate"

[[bin]]
name = "analyze"
